### ISSUE TITLE
Option to select/unselect formats

### ISSUE THREAD

**Issue by pawamoy** [hukkin/mdformat-config#4]
I would like to unselect formatting of TOML snippets, because IMO the result is not that good:

```toml title="pyproject.toml"
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "package-name"
description = "The package description."
version = "0.1.0"
authors = [{name = "Timothée Mazzucotelli", email = "dev@pawamoy.fr"}]
license = "ISC"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["some", "keywords"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]
```

...is formatted to:

```toml title="pyproject.toml"
[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project]
name = "package-name"
description = "The package description."
version = "0.1.0"
license = "ISC"
readme = "README.md"
requires-python = ">=3.7"
keywords = [ "some", "keywords",]
classifiers = [ "Development Status :: 4 - Beta", "Intended Audience :: Developers", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3 :: Only", "Typing :: Typed",]
[[project.authors]]
name = "Timothée Mazzucotelli"
email = "dev@pawamoy.fr"
```

Things I don't like in the formatted block:

- arrays start with a space, but do not end with one
- arrays are inlined (line breaks removed) (this is the most crazy one :sweat_smile:)
- trailing commas are added to already inlined arrays
- trailing commas are not removed after inlining arrays
- inline mappings are moved after the current object
- no space is added before a moved mapping

I suspect you don't do anything special in this project and just load and re-dump the TOML data.

So in the end I'd just like to prevent TOML formatting and just keep JSON and YAML :slightly_smiling_face:
